name: blocgorouter
description: Simple example app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.1
  firebase_ui_auth: ^1.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^7.1.1
  intl: any # uses transitive dependency from flutter_localizations

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true