name: blocgorouter
description: Simple example app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.15.1
  firebase_ui_auth: ^1.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  fvm: ^2.4.1
  go_router: ^10.1.2
  intl: any # uses transitive dependency from flutter_localizations

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1 # 2.4.2 conflicts with ...
  melos: ^3.1.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true